services:
    authentication.handler.login_success_handler:
        class:  AdminBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']

    admin.service.algorithmic_helper:
        class: AdminBundle\Services\AlgorithmicHelper
        arguments:  ["@doctrine.orm.entity_manager"]

    admin.twig.generate_id:
      class: AdminBundle\Twig\GenerateIdExtension
      tags:
        - { name: twig.extension }

    admin.listener.import_listener:
        class: AdminBundle\EventListener\ImportListener
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postRemove, method: postRemove }
    
    admin.validator.quantity_validator:
        class: AdminBundle\Validator\Constraints\QuantityNotOverInventoryValidator
        arguments: ["@request_stack"]
        tags:
            - { name: validator.constraint_validator, alias: quantity_not_over_inventory } 

    admin.validator.unit_price_validator:
        class: AdminBundle\Validator\Constraints\UnitPriceOverCostPriceValidator
        tags:
            - { name: validator.constraint_validator, alias: unit_price_over_cost_price }

    admin.util.bill_util:
        class: AdminBundle\Util\BillUtil
        arguments: ["@doctrine.orm.entity_manager"]

    # admin.listener.import_listener:
    #     class: AdminBundle\EventListener\ImportListener
    #     arguments: ["@service_container"]
    #     tags:
    #         - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
