<?php

namespace AdminBundle\Repository;

/**
 * BillDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
