<?php

namespace AdminBundle\Repository;

/**
 * CoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCoreByYMDProductId($year, $month, $day, $id_product) {
		if($year && $month && $day && $id_product) {
			$query = $this->createQueryBuilder('c')
	            ->select('c')
	            ->where('c.year = :year')
	            ->andWhere('c.month = :month')
	            ->andWhere('c.day = :day')
	            ->andWhere('c.product = :id_product')
	            ->setParameters(
	            	array(
	            		':year' => $year,
	            		':month' => $month,
	            		':day' => $day,
	            		':id_product' => $id_product,
	            	)
	            )
	            ->getQuery();

	    	return $query->getOneOrNullResult();	
		}
			
		return FALSE;
	}
}	
