<?php

namespace AdminBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function byId($id) {
		$results = array();
		if($id) {
			$query = $this->createQueryBuilder('p')
	            ->select('p')
	            ->where('p.id = :id')
	            ->setParameter('id', $id)
	            ->getQuery();

	        $results = $query->getArrayResult();	
		}
		
        return $results;
	}
}

