import_detail_index:
    path:     /list
    defaults: { _controller: "AdminBundle:ImportDetail:index" }
    methods:  GET

import_detail_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:ImportDetail:show" }
    methods:  GET

import_detail_new:
    path:     /new
    defaults: { _controller: "AdminBundle:ImportDetail:new" }
    methods:  [GET, POST]

import_detail_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:ImportDetail:edit" }
    methods:  [GET, POST]

import_detail_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:ImportDetail:delete" }
    methods:  [GET, DELETE]
