provider_index:
    path:     /list
    defaults: { _controller: "AdminBundle:Provider:index" }
    methods:  GET

provider_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Provider:show" }
    methods:  GET

provider_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Provider:new" }
    methods:  [GET, POST]

provider_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Provider:edit" }
    methods:  [GET, POST]

provider_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Provider:delete" }
    methods:  [GET, DELETE]
